media_get_audio_playlist:
    path: /audio/all.{_format}
    defaults: {_controller: MediaBundle:MediaApi:getAudioPlaylist, _format: json}

media_create:
    path:     media/create
    defaults: { _controller: "MediaBundle:MediaApi:create", _format: json }
    methods:  POST